### ISSUE TITLE
Suggestion: highlight selected attribute

### ISSUE THREAD

**Issue by heidieh** [SimonbJohnson/leaftlet-grid-viz#3]
Currently: When the user scrolls over an attribute in the grid, that attribute is mapped; then when they leave the grid area the map continues to display the last attribute but it is no longer clear which attribute that is (unless you remember or analyse the values).
Suggestion: Highlight which attribute is currently being displayed on the map - e.g. display the attribute title in the corner of map and/or bold face the attribute heading text in the grid.

**Comment by SimonbJohnson** [comment]
Fixed in 389a61df0ca0de9b53924a8608df1c19e78ea410
